import { describe, it, expect } from 'vitest';
import * as Exceptions from '../../../domain/exceptions/UserExceptions.js';

describe('UserExceptions', () => {
    it('should instantiate all exceptions correctly', () => {
        const exUserNotFoundException = new Exceptions.UserNotFoundException();
        expect(exUserNotFoundException).toBeInstanceOf(Error);
        expect(exUserNotFoundException.name).toBe('UserNotFoundException');
        const exUserAlreadyActiveException = new Exceptions.UserAlreadyActiveException();
        expect(exUserAlreadyActiveException).toBeInstanceOf(Error);
        expect(exUserAlreadyActiveException.name).toBe('UserAlreadyActiveException');
        const exUserNotInactiveException = new Exceptions.UserNotInactiveException();
        expect(exUserNotInactiveException).toBeInstanceOf(Error);
        expect(exUserNotInactiveException.name).toBe('UserNotInactiveException');
        const exUserInactiveException = new Exceptions.UserInactiveException();
        expect(exUserInactiveException).toBeInstanceOf(Error);
        expect(exUserInactiveException.name).toBe('UserInactiveException');
        const exUserDeletedException = new Exceptions.UserDeletedException();
        expect(exUserDeletedException).toBeInstanceOf(Error);
        expect(exUserDeletedException.name).toBe('UserDeletedException');
        const exUserAlreadyDeletedException = new Exceptions.UserAlreadyDeletedException();
        expect(exUserAlreadyDeletedException).toBeInstanceOf(Error);
        expect(exUserAlreadyDeletedException.name).toBe('UserAlreadyDeletedException');
        const exUserNotDeletedException = new Exceptions.UserNotDeletedException();
        expect(exUserNotDeletedException).toBeInstanceOf(Error);
        expect(exUserNotDeletedException.name).toBe('UserNotDeletedException');
        const exUserBlockedException = new Exceptions.UserBlockedException();
        expect(exUserBlockedException).toBeInstanceOf(Error);
        expect(exUserBlockedException.name).toBe('UserBlockedException');
        const exUserAlreadyBlockedException = new Exceptions.UserAlreadyBlockedException();
        expect(exUserAlreadyBlockedException).toBeInstanceOf(Error);
        expect(exUserAlreadyBlockedException.name).toBe('UserAlreadyBlockedException');
        const exUserNotBlockedException = new Exceptions.UserNotBlockedException();
        expect(exUserNotBlockedException).toBeInstanceOf(Error);
        expect(exUserNotBlockedException.name).toBe('UserNotBlockedException');
        const exUserNotActiveException = new Exceptions.UserNotActiveException();
        expect(exUserNotActiveException).toBeInstanceOf(Error);
        expect(exUserNotActiveException.name).toBe('UserNotActiveException');
        const exEmailAlreadyInUseException = new Exceptions.EmailAlreadyInUseException();
        expect(exEmailAlreadyInUseException).toBeInstanceOf(Error);
        expect(exEmailAlreadyInUseException.name).toBe('EmailAlreadyInUseException');
        const exInvalidCredentialsException = new Exceptions.InvalidCredentialsException();
        expect(exInvalidCredentialsException).toBeInstanceOf(Error);
        expect(exInvalidCredentialsException.name).toBe('InvalidCredentialsException');
        const exInvalidPasswordException = new Exceptions.InvalidPasswordException();
        expect(exInvalidPasswordException).toBeInstanceOf(Error);
        expect(exInvalidPasswordException.name).toBe('InvalidPasswordException');
        const exMissingRequiredUserFieldsException = new Exceptions.MissingRequiredUserFieldsException();
        expect(exMissingRequiredUserFieldsException).toBeInstanceOf(Error);
        expect(exMissingRequiredUserFieldsException.name).toBe('MissingRequiredUserFieldsException');
        const exInvalidUserFieldsException = new Exceptions.InvalidUserFieldsException();
        expect(exInvalidUserFieldsException).toBeInstanceOf(Error);
        expect(exInvalidUserFieldsException.name).toBe('InvalidUserFieldsException');
    });
});
